// 支持的语言列表（按使用频率排序）
export const LANGUAGES = [
  // 主要语言
  { label: '中文 (简体)', value: 'zh' },
  { label: '英语', value: 'en' },
  { label: '日语', value: 'ja' },
  { label: '韩语', value: 'ko' },
  { label: '法语', value: 'fr' },
  { label: '德语', value: 'de' },
  { label: '西班牙语', value: 'es' },
  { label: '俄语', value: 'ru' },
  { label: '意大利语', value: 'it' },
  { label: '葡萄牙语', value: 'pt' },
  { label: '阿拉伯语', value: 'ar' },
  { label: '荷兰语', value: 'nl' },
  { label: '波兰语', value: 'pl' },
  { label: '土耳其语', value: 'tr' },
  { label: '印地语', value: 'hi' },
  { label: '瑞典语', value: 'sv' },
  { label: '挪威语', value: 'no' },
  { label: '丹麦语', value: 'da' },
  { label: '芬兰语', value: 'fi' },
  { label: '捷克语', value: 'cs' },
  { label: '匈牙利语', value: 'hu' },
  { label: '希腊语', value: 'el' },
  { label: '希伯来语', value: 'he' },
  { label: '泰语', value: 'th' },
  { label: '越南语', value: 'vi' },
  { label: '印度尼西亚语', value: 'id' },
  { label: '马来语', value: 'ms' },
  { label: '乌克兰语', value: 'uk' },
  { label: '保加利亚语', value: 'bg' },
  { label: '罗马尼亚语', value: 'ro' },
  { label: '克罗地亚语', value: 'hr' },
  { label: '斯洛伐克语', value: 'sk' },
  { label: '斯洛文尼亚语', value: 'sl' },
  { label: '立陶宛语', value: 'lt' },
  { label: '拉脱维亚语', value: 'lv' },
  { label: '爱沙尼亚语', value: 'et' },
  { label: '加泰罗尼亚语', value: 'ca' },
  { label: '巴斯克语', value: 'eu' },
  { label: '威尔士语', value: 'cy' },
  { label: '爱尔兰语', value: 'ga' },
  { label: '苏格兰盖尔语', value: 'gd' },
  { label: '孟加拉语', value: 'bn' },
  { label: '古吉拉特语', value: 'gu' },
  { label: '马拉地语', value: 'mr' },
  { label: '泰米尔语', value: 'ta' },
  { label: '泰卢固语', value: 'te' },
  { label: '卡纳达语', value: 'kn' },
  { label: '马拉雅拉姆语', value: 'ml' },
  { label: '旁遮普语', value: 'pa' },
  { label: '乌尔都语', value: 'ur' },
  { label: '波斯语', value: 'fa' },
  { label: '普什图语', value: 'ps' },
  { label: '信德语', value: 'sd' },
  { label: '尼泊尔语', value: 'ne' },
  { label: '僧伽罗语', value: 'si' },
  { label: '缅甸语', value: 'my' },
  { label: '哈萨克语', value: 'kk' },
  { label: '吉尔吉斯语', value: 'ky' },
  { label: '塔吉克语', value: 'tg' },
  { label: '乌兹别克语', value: 'uz' },
  { label: '亚美尼亚语', value: 'hy' },
  { label: '阿塞拜疆语', value: 'az' },
  { label: '格鲁吉亚语', value: 'ka' },
  { label: '阿姆哈拉语', value: 'am' },
  { label: '蒙古语', value: 'mn' },
  { label: '藏语', value: 'bo' },
  { label: '老挝语', value: 'lo' },
  { label: '高棉语', value: 'km' },
  { label: '斯瓦希里语', value: 'sw' },
  { label: '豪萨语', value: 'ha' },
  { label: '约鲁巴语', value: 'yo' },
  { label: '阿非利卡语', value: 'af' },
  { label: '马尔加什语', value: 'mg' },
  { label: '塞尔维亚语', value: 'sr' },
  { label: '波斯尼亚语', value: 'bs' },
  { label: '马其顿语', value: 'mk' },
  { label: '阿尔巴尼亚语', value: 'sq' },
  { label: '马耳他语', value: 'mt' },
  { label: '冰岛语', value: 'is' },
  { label: '法罗语', value: 'fo' },
  { label: '卢森堡语', value: 'lb' },
  // 自动检测选项
  { label: '自动检测', value: 'auto' },
];

// 模型信息
export const MODEL_INFOS = {
  'ggml-base.bin': 'Base：速度最快，精度较低，适合快速预览',
  'ggml-small.bin': 'Small：速度快，精度中等，推荐日常使用',
  'ggml-medium.bin': 'Medium：速度较慢，精度高，适合高质量需求',
};

// 常用语言（用于快速选择）
export const POPULAR_LANGUAGES = [
  'zh', 'en', 'ja', 'ko', 'fr', 'de', 'es', 'ru'
];
